name: Deploy immich ML

on:
  push:
    branches:
      - main
    paths:
      - 'immich/immich-machine-learning.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-compose.yml
    with:
      ssh_user: ${{ vars.IMMICH_ML_USER }}
      ssh_host: ${{ vars.IMMICH_ML_HOST }}
      app_directory: immich
      docker_compose_file: immich-machine-learning.yml
    secrets:
      tailscale_authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      env_file_contents: ${{ secrets.IMMICH_DOT_ENV_SECRETS }}