name: Deploy open-webui

on:
  push:
    branches:
      - main
    paths:
      - 'open-webui/open-webui.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/docker-up.yml
    with:
      ssh_user: ${{ vars.IMMICH_ML_USER }}
      ssh_host: ${{ vars.IMMICH_ML_HOST }}
      app_directory: open-webui
      docker_compose_file: open-webui.yml
    secrets:
      tailscale_authkey: ${{ secrets.TAILSCALE_AUTHKEY }}