name: Deploy runner

on:
  push:
    branches:
      - main
    paths:
      - 'action-runner/runner.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/docker-up.yml
    with:
      ssh_user: ${{ vars.IMMICH_SERVER_USER }}
      ssh_host: ${{ vars.IMMICH_SERVER_HOST }}
      app_directory: action-runner
      docker_compose_file: runner.yml
    secrets:
      tailscale_authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      env_file_contents: ${{ secrets.RUNNER_DOT_ENV_SECRETS }}